### PR TITLE
Add schema file

### PR DESCRIPTION
**Pull request by SimonUnge**
## Proposed Changes

Add schema-files that uses supported_ciphers|hashes as validation.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] All tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in related repositories

## Further Comments

If this is a relatively large or complex change, kick off the discussion by
explaining why you chose the solution you did and what alternatives you
considered, etc.

### CODE REVIEW

**Comment by SimonUnge** [comment]
I am happy to add tests too, if required.

**Comment by michaelklishin** [comment]
@SimonUnge I think this is so straighforward that we can do without schema generation tests. One thing I am worried about if these defaults may show up in the generated config files in RabbitMQ's own suites. If so we will have to use `cuttlefish:unset/0` like so

``` erl
{mapping, "connection_max", "rabbit.connection_max",
  [{datatype, [{atom, infinity}, integer]}]}.

{translation, "rabbit.connection_max",
 fun(Conf) ->
  case cuttlefish:conf_get("connection_max", Conf, undefined) of
      undefined -> cuttlefish:unset();
      infinity  -> infinity;
      Val when is_integer(Val) -> Val;
      _         -> cuttlefish:invalid("should be a non-negative integer")
  end
 end
}.
```

**Comment by SimonUnge** [comment]
@michaelklishin I'll give it a try in rabbitmq, if I can figure out bazel enough to use the main branch!

**Comment by michaelklishin** [comment]
@michaelklishin here is [one example](https://github.com/rabbitmq/rabbitmq-server/blob/main/MODULE.bazel#L403-L407) where we use a dependency from a git repo.

**Comment by michaelklishin** [comment]
And [here](https://github.com/rabbitmq/rabbitmq-server/blob/main/MODULE.bazel#L218-L223) is where we define the Cuttlefish dependency (currently consumed from hex.pm).

**Comment by SimonUnge** [comment]
Thank you!

**Comment by SimonUnge** [comment]
Building now. But, we could ofc just use 'unset()' as the code itself has the defaults

**Comment by michaelklishin** [comment]
Let's use `cuttlefish:unset/0` then, it's a standard thing to do in the RabbitMQ codebase.

**Comment by SimonUnge** [comment]
OK, I'll create a new PR.

**Comment by SimonUnge** [comment]
Something like this seems to be required in rabbitmq bazel setup to fetch the file:
```
diff --git a/bazel/BUILD.credentials_obfuscation b/bazel/BUILD.credentials_obfuscation
index e3381d99bd..746a28147e 100644
--- a/bazel/BUILD.credentials_obfuscation
+++ b/bazel/BUILD.credentials_obfuscation
@@ -57,7 +57,11 @@ filegroup(
     ],
 )
 
-filegroup(name = "priv")
+filegroup(
+    name = "priv",
+    srcs = ["priv/schema/credentials_obfuscation.schema"],
+)
+
```

**Comment by michaelklishin** [comment]
@SimonUnge possibly. This is not a plugin, just a dependency, so various code path rules for it can be different (e.g. the `priv` directory will not be automatically included)>

**Comment by SimonUnge** [comment]
Not sure how it works for hex packages to be honest. The above bazel fix worked to get it included when bazel fetch the code from git... I'll do some digging, and maybe ask Rin!

**Comment by lukebakken** [comment]
https://hex.pm/packages/credentials_obfuscation/3.5.0

**Pull request merged**
